### ISSUE TITLE
Plans to open source frontend?

### ISSUE THREAD

**Issue by ChristianMurphy** [edusense/edusense#6]
The [getting started guide](https://github.com/edusense/edusense/blob/master/doc/getting_started.md#edusense-component-overview) mentions

> Frontend (not included in this repository)
> * frontend visualizes processed data, providing useful debug interface. Currently, our edusense repository does not contain this component.

are there plans to open source the front end as well?

**Comment by mudar-memari-cmu** [comment]
Good afternoon Christian,

are there plans to open source the front end as well?
Currently, no but I'm looking into it. 

Hopefully I'll have some more information by the end of week. 

Thank you
Regards,
Mudar Memari

**Comment by ChristianMurphy** [comment]
Thanks @mudar-memari-cmu!
